### ISSUE TITLE
how do i use this?

### ISSUE THREAD

**Issue by mm-psymbl** [ZixiaoWang/tns-urihandler#1]
Hi there

how am i supposed to use this? It says that urihandles.ts is missing and needs to be imported in tsconfig.json.

looks like this plugin isnt compiled properly for use?

**Comment by ZixiaoWang** [comment]
@mm-psymbl Hi, can you please provide more details like which OS you're trying to build?
The official docs mentioned the plugin can use platform-specific index like `index.ios.js` or `index.android.js` and tns will then handle the rest. 
[Plugin Reference](https://docs.nativescript.org/angular/plugins/plugin-reference)

**Comment by mm-psymbl** [comment]
im not an expert in Nativescript but this is what i get when i try to follow your example

`ERROR in ../node_modules/tns-urihandler/urihandler.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /Users/manuelmaestrini/Programming/psymbl/mobile/node_modules/tns-urihandler/urihandler.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at NativeScriptAngularCompilerPlugin.getCompiledFile (/Users/manuelmaestrini/Programming/psymbl/mobile/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:951:23)
    at NativeScriptAngularCompilerPlugin.getCompiledFile (/Users/manuelmaestrini/Programming/psymbl/mobile/node_modules/@nativescript/webpack/plugins/NativeScriptAngularCompilerPlugin.js:29:26)
    at /Users/manuelmaestrini/Programming/psymbl/mobile/node_modules/@ngtools/webpack/src/loader.js:43:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./app/app.component.ts 2:0-44 10:29-39
 @ ./app/app.module.ts
 @ ./main.ts`

![image](https://user-images.githubusercontent.com/78551889/108382270-ec9dc700-7208-11eb-9d9c-0018793c1b61.png)

**Comment by ZixiaoWang** [comment]
Can you provide your NativeScript version and which platform you met the problem with? 
I'll see if the problem can be reproduced.
